iosxr_prefix_lists: Add missing keys ge, eq, le
ansible-collections/cisco.iosxr pull request #230
Opened 2022-04-01 14:54 UTC by ashwini-mhatre

##### SUMMARY

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-04-04 06:48 UTC, ashwini-mhatre commented
recheck

2022-04-04 07:06 UTC, ashwini-mhatre commented
recheck

2022-04-04 07:17 UTC, KB-perByte requested changes

2022-04-04 07:17 UTC, KB-perByte commented on plugins/modules/iosxr_prefix_lists.py
> +    - sample command 1
add relevant commands here

2022-04-04 07:17 UTC, KB-perByte commented on plugins/modules/iosxr_prefix_lists.py
>  # Using merged
can we add an example for the change

2022-04-04 07:18 UTC, ashwini-mhatre commented on plugins/modules/iosxr_prefix_lists.py
>  # Using merged
ack

2022-04-04 07:18 UTC, ashwini-mhatre commented on plugins/modules/iosxr_prefix_lists.py
> +    - sample command 1
ack

2022-04-05 09:28 UTC, ashwini-mhatre commented
recheck

2022-04-05 09:30 UTC, ashwini-mhatre commented
recheck

2022-04-05 14:16 UTC, ashwini-mhatre commented
recheck

2022-04-06 09:40 UTC, KB-perByte approved these changes

2022-04-06 09:41 UTC, ashwini-mhatre commented
recheck

2022-04-06 10:35 UTC, ashwini-mhatre commented
recheck

2022-04-06 11:26 UTC, merged