fix commit confirm
ansible-collections/cisco.iosxr pull request #245
Opened 2022-05-25 14:25 UTC by KB-perByte

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-05-25 19:03 UTC, Qalthos requested changes
I could be wrong, as I don't know the platform well, but it looks to me like the only issue with the code here is that comment and confirmed are mutually exclusive for some obscure reason.

I think the most reasonable solution to which is to emit a warning like `Ignoring commit comment {comment} as it is incompatible with confirmed`

2022-05-26 02:23 UTC, KB-perByte commented on plugins/cliconf/iosxr.py
>                  )
ah, this is a different issue I faced, actually, there is a keen difference between version iosxr v7.0.2 and v7.2.2 
in `7.0.2` - _we used to support_
a `label` can have `comment` _after_ that but a `comment` cannot have `label` after it as _comment is a line_
```
RP/0/RP0/CPU0:ios(config)#hostname R1
RP/0/RP0/CPU0:ios(config)#commit label hostname comment ?
  LINE  Comment for this commit (Max 60 characters)
RP/0/RP0/CPU0:ios(config)#commit label hostname comment good?
LINE
  <cr>  Commit the configuration changes via pseudo-atomic operation
```
and `commit confirmed` is sane as the options here are limited and make sense 
```
RP/0/RP0/CPU0:ios(config)#commit confirmed ?              
  <30-65535>  Seconds until rollback unless there is a confirming commit
  minutes     Specify the rollback timer in the minutes
  show-error  Displays commit failures immediately
  <cr>        Commit the configuration changes via pseudo-atomic operation
```
in `7.2.2` - _we support_
label and comment is mutually exclusive 
```
RP/0/RP0/CPU0:10.0.150.115(config)#hostname r1 
RP/0/RP0/CPU0:10.0.150.115(config)#commit label hostname ?
  show-error  Displays commit failures immediately
  <cr>        Commit the configuration changes via pseudo-atomic operation
RP/0/RP0/CPU0:10.0.150.115(config)#commit comment line comment ?
LINE
  <cr>  Commit the configuration changes via pseudo-atomic operation
```
ref of them being mutually exclusive- 
```
RP/0/RP0/CPU0:10.0.150.115(config)#hostname r1 
RP/0/RP0/CPU0:10.0.150.115(config)#commit comment line comment 
Thu May 26 02:12:50.298 UTC
RP/0/RP0/CPU0:r1(config)#commit label lbl1
Thu May 26 02:13:16.598 UTC
No configuration changes to commit.
```
now `commit confirmed` is different here - 
```
RP/0/RP0/CPU0:r1(config)#commit confirmed ?
  <30-65535>  Seconds until rollback unless there is a confirming commit
  comment     Assign a comment to this commit
  label       Assign a label to this commit
  minutes     Specify the rollback timer in the minutes
  show-error  Displays commit failures immediately
  <cr>        Commit the configuration changes via pseudo-atomic operation
```
we have support to `timeout` in `cliconf` from the above options, not _label_ or _comment_
and the timeout attribute explicitly says if we don't add a `commit` after a `commit confirmed <timeout>` it rollbacks.

2022-05-26 02:26 UTC, KB-perByte commented on plugins/cliconf/iosxr.py
> +            self.send_command("commit")
IMO as we plan to support 7.2.2 firing commands individually for an attribute is supposed to make it work on 7.0.2 and 7.2.2, as none of the combinations that the old code produced makes a valid command in the supported version. yes, we might need to handle the extra commit we are pushing based on the version number here.

2022-05-31 13:12 UTC, Qalthos commented on plugins/cliconf/iosxr.py
>                  )
I'm going to take some things out of order here

> ah, this is a different issue I faced, actually, there is a keen difference between version iosxr v7.0.2 and v7.2.2 in `7.0.2` - _we used to support_ a `label` can have `comment` _after_ that but a `comment` cannot have `label` after it as _comment is a line_

Right, so in this case we just have to make sure the options are in the right order.

> in `7.2.2` - _we support_ label and comment is mutually exclusive

Those are both config options, so we should probably enforce that at the module level after a version gate. Do you know which iosxr version changed this?

> and `commit confirmed` is sane as the options here are limited and make sense

> now `commit confirmed` is different here -

So it looks like this is entirely backward from the previous way. In 7.0.2, confirmed needed to be the last clause, and in 7.2.2 it needs to be the first, but it looks like they can still be used together, albeit only for label in 7.0.2

> we have support to `timeout` in `cliconf` from the above options, not _label_ or _comment_ and the timeout attribute explicitly says if we don't add a `commit` after a `commit confirmed <timeout>` it rollbacks.

I have no problem with this in general, but it seems like label and confirmed are completely compatible, just not with the same order between versions.

2022-05-31 19:25 UTC, sean-m-sullivan commented on plugins/cliconf/iosxr.py
> +            self.send_command("commit")
Agreed on the other one, We should not be sending commit immediately here, as it nullifies any reason to even use commit confirmed.

2022-05-31 19:29 UTC, sean-m-sullivan requested changes
I am not liking these changes, It looks like it breaks things and makes commit confirm unusable. Going to do some testing on this and/or see about another workaround. I have a 6.6.3 and a 7.3.2  to test on, and have a working alternative when comment isn't used to use commit confirmed, but the current collection as is, does not work with 6.6.3 because of the default comment being populated.

2022-05-31 21:07 UTC, Qalthos commented on plugins/cliconf/iosxr.py
> +            self.send_command("commit")
https://github.com/ansible-collections/cisco.iosxr/blob/main/plugins/cliconf/iosxr.py#L443 looks like it is trying to work around the "abort between tasks" issue, I'm just not sure that it's doing it properly.

2022-06-07 09:56 UTC, KB-perByte commented
Closing this out, in favor of https://github.com/ansible-collections/cisco.iosxr/pull/252
CC @sean-m-sullivan @Qalthos

2022-06-07 09:56 UTC, closed without merging