Update bgp_neighbor_address_family option mutually exclusive
ansible-collections/cisco.iosxr pull request #331
Opened 2023-02-02 07:18 UTC by ashwini-mhatre

##### SUMMARY

fixes: https://github.com/ansible-collections/cisco.iosxr/issues/325

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-02-02 13:41 UTC, Qalthos requested changes
We're deep in the argspec, but hopefully this is clear enough for a better changelog entry?

2023-02-02 13:41 UTC, Qalthos commented on changelogs/fragments/Bugfix_325.yaml
> +  - Update 'bgp_neighbor_address_family' options mutually exclusive.
```suggestion
  - bgp_neighbor_address_family - mark ``soft_reconfiguration`` suboptions ``set``, ``always``, and ``inheritance_disable`` as mutually exclusive. (https://github.com/ansible-collections/cisco.iosxr/issues/325)
```

2023-02-06 05:43 UTC, ashwini-mhatre commented on changelogs/fragments/Bugfix_325.yaml
> +  - Update 'bgp_neighbor_address_family' options mutually exclusive.
ack

2023-02-06 06:26 UTC, KB-perByte approved these changes

2023-02-06 07:00 UTC, merged