Update bgp global docs
ansible-collections/cisco.iosxr pull request #376
Opened 2023-04-19 07:31 UTC by rohitthakur2590

##### SUMMARY

##### ISSUE TYPE

 
- Docs Pull Request
 

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-04-19 13:32 UTC, Qalthos requested changes
Probably also empty lines before and after the tasks themselves instead of a commented line.

2023-04-19 13:32 UTC, Qalthos commented on plugins/modules/iosxr_bgp_global.py
> +#
There should be at least some break between examples.
```suggestion

```

2023-04-19 13:32 UTC, Qalthos commented on plugins/modules/iosxr_bgp_global.py
> +#
```suggestion

```

2023-04-19 13:32 UTC, Qalthos commented on plugins/modules/iosxr_bgp_global.py
>  #
```suggestion

```

2023-04-19 13:32 UTC, Qalthos commented on plugins/modules/iosxr_bgp_global.py
> +#
```suggestion

```

2023-04-27 10:35 UTC, ashwini-mhatre approved these changes

2023-04-27 10:46 UTC, merged