Add missing options in afi and safi in address-family of bgp_template…
ansible-collections/cisco.iosxr pull request #472
Opened 2024-02-13 09:34 UTC by ashwini-mhatre

…s RM.

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-02-13 11:34 UTC, Ruchip16 approved these changes

2024-02-13 11:35 UTC, NilashishC requested changes

2024-02-13 11:35 UTC, NilashishC commented on plugins/modules/iosxr_bgp_templates.py
> +                    choices: [ 'ipv4', 'ipv6', 'vpn4', 'vpn6', 'link-state', 'l2vpn']
Can we have unit tests to verify these?

2024-02-14 08:07 UTC, NilashishC approved these changes

2024-02-14 08:08 UTC, NilashishC commented on changelogs/fragments/bugfix_bgp_templates.yaml
> +bugfixes:
These are new options. Should be minor_changes.

2024-02-14 08:37 UTC, merged