Remove deprecated module
ansible-collections/cisco.iosxr pull request #479
Opened 2024-03-21 19:00 UTC by Ruchip16

##### SUMMARY

- iosxr_logging - Remove deprecated logging legacy module

##### ISSUE TYPE

-  Remove deprecated module

##### COMPONENT NAME

`iosxr_logging`

2024-03-22 05:57 UTC, ashwini-mhatre commented
please remove unit test case file also if any

2024-03-22 05:59 UTC, Ruchip16 commented
> please remove unit test case file also if any

yes, there is no unit test-case file for `iosxr_logging`

2024-03-26 13:37 UTC, NilashishC requested changes
The meta/runtime.yml entry should also be removed.

2024-03-26 13:37 UTC, NilashishC commented on changelogs/fragments/remove_deprecated.yml
> +---
Please refer to https://github.com/ansible-collections/cisco.nxos/pull/836/files#diff-044354a2e5989396b9168d5dde63bd5196447bfcf661637e7433555b532c50c6R1-R8 for changelog entry.

2024-03-27 06:30 UTC, KB-perByte approved these changes

2024-03-27 06:42 UTC, NilashishC approved these changes

2024-03-27 07:01 UTC, merged