Add `vrf_address_family` module
ansible-collections/cisco.iosxr pull request #489
Opened 2024-05-13 05:34 UTC by Ruchip16

##### SUMMARY

This PR adds support for `iosxr_vrf_address_family` resource module

##### DESCRIPTION

 Here is the [model](https://github.com/ansible-network/resource_module_models/pull/243) design for the `iosxr_vrf_address_family` resource module

 

##### ISSUE TYPE

- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

`cisco.iosxr.iosxr_vrf_address_family`

##### MILESTONES

- [x] Parsing entire argspec ( which covers gathered and parsed state )
- [x] Merged and Deleted state working
- [x] Replaced state working
- [x] Overridden state working
- [x]  Unit tests & Integration tests

2024-07-01 09:52 UTC, roverflow commented on tests/integration/targets/iosxr_vrf_address_family/tests/common/_remove_config.yaml
> +  register: result
might have to add a new line here

2024-07-01 09:52 UTC, roverflow commented on tests/integration/targets/iosxr_vrf_address_family/tests/common/deleted.yaml
> +    # - name: Assert that before dicts are correctly generated
might have to remove this commented code if it is not going to be used

2024-07-01 09:52 UTC, roverflow commented on README.md
> +[cisco.iosxr.iosxr_vrfs](https://github.com/ansible-collections/cisco.iosxr/blob/main/docs/cisco.iosxr.iosxr_vrfs_module.rst)|Manages global VRF configuration.
should this be here

2024-07-02 05:53 UTC, Ruchip16 commented on plugins/module_utils/network/iosxr/facts/vrf_address_family/vrf_address_family.py
> +        af = af_data.get("address_families", {})
no i am converting the dict to  list of dict here

2024-07-03 08:57 UTC, rohitthakur2590 requested changes

2024-07-03 08:57 UTC, rohitthakur2590 commented on plugins/modules/iosxr_vrf_address_family.py
> +# before: {}
why `before` is a dict here?

2024-07-04 13:24 UTC, rohitthakur2590 requested changes

2024-07-04 13:24 UTC, rohitthakur2590 commented on README.md
> +[cisco.iosxr.iosxr_vrf_address_family](https://github.com/ansible-collections/cisco.iosxr/blob/main/docs/cisco.iosxr.iosxr_vrf_address_family_module.rst)|Resource module to configure VRF Address fami
Please add the redirect for the RM in meta/runtime/.yml file

2024-07-05 07:08 UTC, rohitthakur2590 approved these changes

2024-07-24 13:11 UTC, KB-perByte requested changes

2024-07-24 13:11 UTC, KB-perByte commented on changelogs/fragments/add_vrfs_module.yaml
> +  - Adds a new module `iosxr_vrfs` to manage VRFs on Cisco IOS-XR devices.
Can we please make it just one changelog entry, we need not add 3 list entries for one module that is being added.

2024-07-24 13:11 UTC, KB-perByte commented on plugins/modules/iosxr_vrf_address_family.py
> +# RP/0/0/CPU0:iosxr-02#show running-config vrf
Simplify the hostname, looks cleaner and remove the timestamp please

2024-07-24 13:11 UTC, KB-perByte commented on plugins/modules/iosxr_vrf_address_family.py
> +# Fri Feb  9 07:02:35.789 UTC
^ the timestamp can be removed -- applies to all the examples below

2024-07-26 14:47 UTC, KB-perByte approved these changes

2024-07-26 19:14 UTC, merged